# Generated by Django 2.2.6 on 2019-11-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'role'), ('event', 'competitor')},
        ),
    ]
